### ISSUE TITLE
If you got the power, would you like to stay and live in Syria or move to Canada?

### ISSUE THREAD

**Issue by AAlakkad** [ahmadnassri/ama#16]
In another world, can you do what you've done while you in Syria? or that's impossible?
I'm in Syria right now, what to ask this question to someone who tried living out.

**Comment by ahmadnassri** [comment]
impossible.

neither the culture, the economy nor the technology would have facilitated for me to do what I do today, learn what I learned, meet the people I know, or grow as a person.

my advise to people in Syria, regardless of the war. GET OUT. learn about the world, get your own true perspective, then decide if you want to come back (and hopefully affect change) or stay out and build your life away from the corrupting influence of a culture that's at least 50 years behind the rest of the modern world.
