### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [ahmadnassri/ama#2]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by ahmadnassri** [comment]
![image](https://cloud.githubusercontent.com/assets/183195/8631555/21827b86-2747-11e5-946f-c4fa3951f816.png)

**Comment by ahmadnassri** [comment]
and that's it, no more apps anywhere.

**Comment by pearlchen** [comment]
Folders FTW
