### ISSUE TITLE
Do you like clowns?

### ISSUE THREAD

**Issue by sindresorhus** [ahmadnassri/ama#6]
Be honest.

**Comment by ahmadnassri** [comment]
I find them boring ... currently there's an ad (unskippable) on youtube that's recurring and targeted to my profile it seems, featuring a clown on a train ... 

I should "NO" at the screen everytime it comes on.

**Comment by sindresorhus** [comment]
Follow-up question. Would you rather be a clown or a duck-sized horse?

**Comment by ahmadnassri** [comment]
clown, so I can troll people and get away with it.
