### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [ahmadnassri/ama#9]

**Comment by ahmadnassri** [comment]
my (older) cousin bought a computer (a rare thing in Damascus, Syria) ~25 years ago ... I was fascinated, with the games of course at that age (5-6) kept visiting his place to play them games.

I was spending so much time there my parents barely got to see me, a few years later, my dad bought a computer, which I immediately glued myself on, and started playing, shortly after stopped working (windows!!!!! */me shakes fist in air*) and being too scared to have my dad know it broke, I tried to figure it out myself ... 

once I got into configurations / installations of dos, windows, and tinkering with motherboard and hard ware setup, my interest in gaming faded away and tinkering/hacking became more satisfying ... 

programming came as a natural progression, soon after I started cracking DLLs and patching EXEs ;)

**Comment by ahmadnassri** [comment]
related: been on Linux since 2007, never looked back.
